# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
    # check these on https://fabricmc.net/develop
    minecraft_version=25w46a
    yarn_mappings=25w46a+build.2
    loader_version=0.17.3

# Mod Properties
    mod_version=0.11.0-alpha.1
    maven_group=net.gnomecraft
    archives_base_name=ductwork

# Dependencies
    fabric_version=0.138.4+1.21.11
    cooldowncoordinator_version=0.9.0-alpha.1
    clothconfig_version=20.0.148
    modmenu_version=17.0.0-alpha.1
