# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
    # check these on https://fabricmc.net/develop
    minecraft_version=26.1
    loader_version=0.19.2

# Mod Properties
    mod_version=0.12.1
    maven_group=net.gnomecraft
    archives_base_name=ductwork

# Dependencies
    fabric_version=0.145.1+26.1
    cooldowncoordinator_version=0.10.0
    clothconfig_version=26.1.154
    modmenu_version=18.0.0
